### ISSUE TITLE
Data Readers with Auto Schema and Auto Class

### ISSUE THREAD

**Issue by albertodema** [salesforce/TransmogrifAI#78] opened 2018-08-22 11:36 UTC
**Problem**
Actually DataReaders need a case class or type to load the data inside a data frame, requesting the developer to code upfront the case class representing the schema of the data .

**Solution**
Enable the option to automatically infer schema and class in the data loaders. 

**Alternatives**
Add a way to pass the case class at runtime, at the moment it is only possible at compile time.

**Comment by tovbinm** [comment] 2018-08-22 18:37
You don't have to define a case class, but it's a preferred approach because it provides us with type safety guarantees.

You can define a data reader that materializes a Dataframe without defining a type, i.e use `org.apache.spark.sql.Row` as a data reader type:

```scala
import org.apache.spark.sql.Row
import com.salesforce.op.readers._

 // Load Dataframe with Spark
val dataframe: DataFrame = ???

// Define reader type or type Row
class RowReader(
  val readPath: Option[String] = None,
  val key: Row => String
)(implicit val wtt: WeakTypeTag[Row]) extends DataReader[Row] {
  override def read(params: OpParams)(implicit spark: SparkSession): Either[RDD[Row], Dataset[Row]] = Right(dataframe)
}
// Define a row reader and use it in your workflow
val rowReader = new RowReader(key = _.get(0).toString /* extract your record key function */ )
```

On top of that you can also generate features from the provided Dataframe, i.e:
```scala
val (response, features) = val (survived, predictors) = FeatureBuilder.fromDataFrame[RealNN](dataframe, response = "survived")
```

**Comment by tovbinm** [comment] 2018-08-22 18:48
If you happen to be loading a CSV file you can also use `CSVAutoReader` that automatically infers CSV schema from the data:
```
val csvReader = new CSVAutoReader[GenericRecord](key = _.get(0).toString)
```

**Comment by tillbe** [comment] 2018-08-22 20:29
The caveat with the automatic schema inferring is that it will only infer base types, not types such as PickList, ComboBox and others. To get the most out of the AutoML capabilities, specifying the types would be very helpful!

**Comment by snabar** [comment] 2018-08-23 03:35
@albertodema there are few different ways to achieve this and some may be better suited to your end goal than others. Would you be able to share more specific info on what you are trying to achieve?

**Comment by albertodema** [comment] 2018-08-23 12:07
I tried both options:
1) Option with CSVAutoReader does not work because I cannot use it with FeatureBuilder from DataFrame . if you try something like:
val csvRead = new CSVAutoReader[GenericRecord](key = _.get(0).toString,readPath = pathToData).readDataset().toDF()
you will have 
 Unable to find encoder for type stored in a Dataset.  Primitive types (Int, String, etc) and Product types (case classes) are supported by importing spark.implicits._  Support for serializing other types will be added in future releases.
2) Option with RowReader works but still I still need to create the data frame and pass it to the feature builder 

My use case is the following: after some data collection/data prep , data coming from difference sources is now sitting on a filesystem (hdfs or s3 or others) and I would like to use transmograficai in combination with a simple command line where I pass file location , target column, algorithm type (Binary or Regression or... ) and I can have a model as result with the corresponding summary.

**Comment by tovbinm** [comment] 2018-08-24 03:30
We do not offer abilities neither to detect key columns, nor guess the problem type (binclass/multiclass/regression/etc). 

What we do offer is a generic tool that can help you build an application for your particular problem. You at least has to specify
1. initial data loading (i.e. `DataReader` or `RDD[T]` / `Dataset[T]`)
2. predictor definitions (or use `FeatureBuilder.fromDataframe` to materialize some basic ones)
3. response definition

You can start by extending `OpApp` base class, which would provide you with command line interface or you borrow an inspiration from it and just extend standard `scala.App` base class.

**Comment by snabar** [comment] 2018-08-24 15:57
Additionally, given an input avro schema, our cli tool code-gens a full project that you can go in and edit (change the FeatureBuilders for instance). 
https://docs.transmogrif.ai/en/latest/examples/Bootstrap-Your-First-Project.html#

**Comment by tovbinm** [comment] 2018-09-01 04:47
@albertodema were you able to figure everything out?

**Comment by albertodema** [comment] 2018-09-06 20:08
Hi thanks for your help, I was able to figure out how to handle those points.
I created this website http://mlforall.azurewebsites.net/ (alpha version) that is my experiment to let a bigger audience play with TransmogrifAI. Let me know if you like it!

**Comment by tovbinm** [comment] 2018-09-06 20:16
That's very cool! Let me check it out.

**Comment by albertodema** [comment] 2018-09-06 20:20
One advice : the csv needs headers, otherwise crashes 👎

**Comment by tovbinm** [comment] 2018-09-06 21:51
I just tried uploading the https://github.com/salesforce/TransmogrifAI/blob/master/test-data/PassengerDataAllWithHeader.csv and it did not seem to work ;(

**Comment by albertodema** [comment] 2018-09-07 02:36
Found your request and also a bug !
http://mlforall.azurewebsites.net/Home/Status?UniqueId=ab9c6ec2-06a6-4d27-9810-cceb598dc244
Basically it seems that if your first request goes in error (the first one was without headers) the UI does not show you the new request id.

**Comment by tovbinm** [comment] 2018-09-07 04:16
Ah, nice. Consider exposing ab it more details on the final status. You can get them through [model insights](https://scaladoc.transmogrif.ai/index.html#com.salesforce.op.OpWorkflowModel@modelInsights(feature:com.salesforce.op.features.OPFeature):com.salesforce.op.ModelInsights)

I am going to close this issue for now.

**Closed by tovbinm** 2018-09-07 04:16 UTC
